# Generated by Django 3.1.2 on 2020-11-10 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_second_review', models.BooleanField(default=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('second_review', 'Second Review'), ('clarification', 'Clarification Sought'), ('rejected', 'Rejected')], default='pending', max_length=120)),
                ('rejection_reason', models.CharField(blank=True, choices=[('non_serious_enquiry', 'Non Serious Enquiry'), ('out_of_scope', 'Out Of Scope'), ('not_suitable', 'Not Suitable'), ('disagreement_on_terms', 'Disagreement On Terms'), ('others', 'Others (Mention)')], max_length=120, null=True)),
                ('comment', models.TextField()),
                ('send_email', models.BooleanField(default=True)),
                ('first_eval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='mails.mail')),
                ('second_eval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_evaluator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
