# Generated by Django 3.1.2 on 2020-11-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('agency', 'Advertising/Media Agency'), ('organizer', 'Event Organizer'), ('label', 'Label'), ('music_company', 'Music Company'), ('tv_channel', 'TV Channel'), ('radio_station', 'Radio Station'), ('publication', 'Publication'), ('streaming_app', 'Streaming App'), ('series_producer', 'TV/ Web Series Producer'), ('film_producer', 'Film Producer'), ('artist_manager', 'Artist Manager'), ('college', 'College'), ('corporate_body', 'COrporate Body'), ('recording_studio', 'Recording Studio'), ('other', 'Other')], default='other', max_length=255)),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, choices=[('record_deals', 'Record Deals'), ('artist_management', 'Artist Management'), ('talent_contest', 'Talent Contest'), ('music_production', 'Music Production'), ('influencer_marketing', 'Influencer Marketing'), ('collaboration', 'Collaboration'), ('retail_outlets', 'Licensing For Retail Outlets'), ('series_or_film', 'Licensing For Series Or Film'), ('radio_or_platforms', 'Radio Or Platforms'), ('gigs', 'Book Artists/Bands For Gigs'), ('broadcast', 'Music Videos For Broadcast')], max_length=100, null=True)),
                ('partner_type', models.CharField(choices=[('college', 'College'), ('organization', 'Organization'), ('individual', 'Individual'), ('other', 'Other')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('college', models.CharField(blank=True, max_length=50, null=True)),
                ('college_activity', models.CharField(blank=True, choices=[('music_contest', 'Music Contest'), ('college_festival', 'College Festival')], max_length=50, null=True)),
                ('budget', models.CharField(blank=True, choices=[('upto_one_lac', 'Upto Rs 1 L'), ('one_to_two_lac', 'Rs 1L - 2L'), ('two_to_four_lac', 'Rs 2L- 4L'), ('more_than_four_lac', 'Rs 4L +')], max_length=20, null=True)),
                ('event_title', models.CharField(max_length=100)),
                ('date_of_event', models.DateTimeField(blank=True, null=True)),
                ('prizes', models.CharField(blank=True, max_length=500, null=True)),
                ('org_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('business_id', models.ManyToManyField(to='leads.Business')),
                ('genre_id', models.ManyToManyField(to='leads.Genre')),
                ('language_id', models.ManyToManyField(to='leads.Language')),
            ],
        ),
    ]
