# Generated by Django 3.1.2 on 2020-11-10 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('agency', 'Advertising/Media Agency'), ('organizer', 'Event Organizer'), ('label', 'Label'), ('music_company', 'Music Company'), ('tv_channel', 'TV Channel'), ('radio_station', 'Radio Station'), ('publication', 'Publication'), ('streaming_app', 'Streaming App'), ('series_producer', 'TV/ Web Series Producer'), ('film_producer', 'Film Producer'), ('artist_manager', 'Artist Manager'), ('college', 'College'), ('corporate_body', 'COrporate Body'), ('recording_studio', 'Recording Studio'), ('other', 'Other')], default='other', max_length=255)),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, choices=[('record_deals', 'Record Deals'), ('artist_management', 'Artist Management'), ('talent_contest', 'Talent Contest'), ('music_production', 'Music Production'), ('influencer_marketing', 'Influencer Marketing'), ('collaboration', 'Collaboration'), ('retail_outlets', 'Licensing For Retail Outlets'), ('series_or_film', 'Licensing For Series Or Film'), ('radio_or_platforms', 'Radio Or Platforms'), ('gigs', 'Book Artists/Bands For Gigs'), ('broadcast', 'Music Videos For Broadcast')], max_length=100, null=True)),
                ('partner_type', models.CharField(choices=[('college', 'College'), ('organization', 'Organization'), ('individual', 'Individual'), ('other', 'Other')], max_length=50)),
                ('evaluator', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('college_name', models.CharField(blank=True, max_length=50, null=True)),
                ('college_activity', models.CharField(blank=True, choices=[('music_contest', 'Music Contest'), ('college_festival', 'College Festival')], max_length=50, null=True)),
                ('budget', models.CharField(blank=True, choices=[('upto_one_lac', 'Upto Rs 1 L'), ('one_to_two_lac', 'Rs 1L - 2L'), ('two_to_four_lac', 'Rs 2L- 4L'), ('more_than_four_lac', 'Rs 4L +')], max_length=20, null=True)),
                ('event_title', models.CharField(max_length=100)),
                ('college_music_contest', models.CharField(blank=True, choices=[('band_battle_hindi', 'Battle Of Bands (Hindi)'), ('band_battle_english', 'Battle Of Bands (English)'), ('solo_singing', 'Solo Singing Contest'), ('others', 'Others')], max_length=120, null=True)),
                ('date_of_event', models.DateTimeField(blank=True, null=True)),
                ('prizes', models.CharField(blank=True, max_length=500, null=True)),
                ('org_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('pending_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('second_review', 'Second Review'), ('clarification', 'Clarification Sought'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('other', models.TextField(blank=True, null=True)),
                ('business_id', models.ManyToManyField(to='leads.Business')),
                ('genre_id', models.ManyToManyField(to='leads.Genre')),
                ('language_id', models.ManyToManyField(to='leads.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
