# Generated by Django 3.1.2 on 2020-11-20 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0004_auto_20201120_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('assamese', 'Assamese'), ('bengali', 'Bengali'), ('bodo', 'Bodo'), ('dogri', 'Dogri'), ('gujrati', 'Gujarati'), ('hindi', 'Hindi'), ('kannada', 'Kannada'), ('kashmiri', 'Kashmiri'), ('konkani', 'Konkani'), ('malayalam', 'Malayalam'), ('manipuri', 'Manipuri'), ('marathi', 'Marathi'), ('maithili', 'Maithili'), ('nepali', 'Nepali'), ('oriya', 'Oriya'), ('punjabi', 'Punjabi'), ('sanskrit', 'Sanskrit'), ('santhali', 'Santhali'), ('sindhi', 'Sindhi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('urdu', 'Urdu')], max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
