# Generated by Django 3.1.2 on 2020-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20201120_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(choices=[('agency', 'Advertising/Media Agency'), ('organizer', 'Event Organizer'), ('label', 'Label'), ('music_company', 'Music Company'), ('tv_channel', 'TV Channel'), ('radio_station', 'Radio Station'), ('publication', 'Publication'), ('streaming_app', 'Streaming App'), ('series_producer', 'TV/ Web Series Producer'), ('film_producer', 'Film Producer'), ('artist_manager', 'Artist Manager'), ('college', 'College'), ('corporate_body', 'Corporate Body'), ('recording_studio', 'Recording Studio'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
