# Generated by Django 3.1.2 on 2020-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20201121_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='evaluator',
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
