# Generated by Django 3.1.2 on 2020-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20201122_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='event_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
