# Generated by Django 3.1.2 on 2020-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20201123_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_id',
            field=models.ManyToManyField(blank=True, null=True, to='leads.Business'),
        ),
    ]
