# Generated by Django 3.1.2 on 2020-11-25 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0011_auto_20201123_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='event_city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='City Of Event/Gig'),
        ),
        migrations.AddField(
            model_name='lead',
            name='gigs',
            field=models.CharField(blank=True, choices=[('corporate_gig', 'Corporate Gig'), ('festival', 'Festival'), ('private_function', 'Private Function')], max_length=120, null=True, verbose_name='Type Of Gigs'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='activity',
            field=models.CharField(blank=True, choices=[('record_deals', 'Record Deals'), ('artist_management', 'Artist Management'), ('talent_contest', 'Talent Contest'), ('music_production', 'Music Production'), ('influencer_marketing', 'Influencer Marketing'), ('collaboration', 'Collaboration'), ('retail_outlets', 'Licensing For Retail Outlets'), ('series_or_film', 'Licensing For Series Or Film'), ('radio_or_platforms', 'Radio Or Platforms'), ('gigs', 'Book Artists/Bands For Gigs'), ('broadcast', 'Music Videos For Broadcast')], max_length=100, null=True, verbose_name='Activity For Which You Would Like To Work With Songdew'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, choices=[('upto_one_lac', 'Upto Rs 1 L'), ('one_to_two_lac', 'Rs 1L - 2L'), ('two_to_four_lac', 'Rs 2L- 4L'), ('more_than_four_lac', 'Rs 4L +')], max_length=20, null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='business_id',
            field=models.ManyToManyField(blank=True, null=True, to='leads.Business', verbose_name='Businesses'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City Of Partner'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='college_activity',
            field=models.CharField(blank=True, choices=[('music_contest', 'Music Contest'), ('college_festival', 'College Festival')], max_length=50, null=True, verbose_name='College Activity'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='college_music_contest',
            field=models.CharField(blank=True, choices=[('band_battle_hindi', 'Battle Of Bands (Hindi)'), ('band_battle_english', 'Battle Of Bands (English)'), ('solo_singing', 'Solo Singing Contest'), ('others', 'Others')], max_length=120, null=True, verbose_name='College Music Contest'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='college_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name Of College (for college)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Of Event/Opportunity'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='event_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name Of Event/Opportunity'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='genre_id',
            field=models.ManyToManyField(blank=True, to='leads.Genre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='language_id',
            field=models.ManyToManyField(blank=True, to='leads.Language', verbose_name='Language Of Gig/Music Event'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='org_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name Of Organization'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('college', 'College'), ('organization', 'Organization'), ('individual', 'Individual'), ('other', 'Other')], max_length=50, null=True, verbose_name='Partner Type'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='prizes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Prizes'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
