# Generated by Django 3.1.2 on 2020-11-10 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(blank=True, max_length=120, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=120, null=True)),
                ('college_name', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('about', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('opportunity_category', models.CharField(blank=True, max_length=120, null=True)),
                ('offering', models.TextField(blank=True, null=True)),
                ('number_of_artists', models.IntegerField(blank=True, null=True)),
                ('if_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('month', 'Monthly'), ('quarter', 'Quarterly'), ('six_months', 'Six Months'), ('yearly', 'Yearly')], max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('college_activity', models.CharField(blank=True, max_length=120, null=True)),
                ('date_of_event', models.DateField(blank=True, null=True)),
                ('college_music_contest', models.CharField(blank=True, choices=[('band_battle_hindi', 'Battle Of Bands (Hindi)'), ('band_battle_english', 'Battle Of Bands (English)'), ('solo_singing', 'Solo Singing Contest'), ('others', 'Others')], max_length=120, null=True)),
                ('prizes', models.CharField(blank=True, max_length=500, null=True)),
                ('budget', models.CharField(blank=True, choices=[('upto_one_lac', 'Upto Rs 1 L'), ('one_to_two_lac', 'Rs 1L - 2L'), ('two_to_four_lac', 'Rs 2L- 4L'), ('more_than_four_lac', 'Rs 4L +')], max_length=120, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('contact_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_1_detail', to='details.contact')),
                ('contact_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_2_detail', to='details.contact')),
                ('genre_id', models.ManyToManyField(related_name='details', to='leads.Genre')),
                ('language_id', models.ManyToManyField(related_name='details', to='leads.Language')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
