# Generated by Django 3.1.2 on 2020-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
