# Generated by Django 3.1.2 on 2020-11-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20201129_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='event_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
